sudo: required
services:
  - docker


before_install:
  - docker build -t denis/docker-react -f Dockerfile.dev .

script:
  - docker run denis/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECTRET_KEY
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env-1"
  bucket_name: "elasticbeanstalk-us-east-2-784308828437"
  bucket_path: "docker-react"
